### ISSUE TITLE
Permit

### ISSUE THREAD

**Issue by acvaughan** [hiscom/hispid#10]
We need to include permit in HISPID. With the Nagoya Protocol in force as of 12th October, we need to be able to prove to collaborators and grant agencies that any genetic resources derived from our specimens were legally acquired. The loan and exchange of specimens to or from countries that have ratified the Protocol will also be affected, if they are to be used for the derivation of genetic material. As well as being required by the Nagoya Protocol, recording permit details is just good collections management practice.

Note that Australia has not yet ratified the agreement, but is starting to implement it (the approach of the Austn govt is to implement first, then ratify, rather than ratify first then figure out how to implement it). There will be different legislative requirements in different jurisdictions due to differing interpretations of the Protocol, but the Australian interpretation is that it only applies to specimens collected after 12 October 2014. Specimens collected - and genetic resources derived from specimens collected - prior to 12 October 2014 are not covered by the Protocol in the Australian interpretation, but may be considered to be bound by the Protocol by other countries' interpretations. The Department of Environment is looking into giving state and territory museums and herbaria 'trusted institution' status to cover cases where permits are unavailable.

We may need more than one permit field (permit number, permit type, permit date etc.). The Global Genome Biodiversity Network (GGBN) is developing permit terms and vocabulary that can be used with the Occurrence Core and Material Sample Core in Darwin Core, and with the ABCDGGBN implementation of ABCD: http://terms.tdwg.org/wiki/GGBN_Permit_Vocabulary.

More detail on the Nagoya Protocol can be found here: http://bit.ly/1zmtvQe

**Comment by AaronWilton** [comment]
The following fields have been proposed from the workshop:  (name and description only listed here)
**permitType**:  Type of permit.
**permitReferenceNumber**: Reference number allocated to the permit by the issuing authority.
**permitIssuedBy**: Name of the authority by whom the permit was issued.
**permitIssuedTo**: Name(s) of the person(s) or organisation to whom the permit was issued.
**permitIssuedDate**: Date the permit was issued.
**permitValidDate**:  Date or period for which the permit is valid.
**permitStatus**: Status of the permit.
**permitConditions**: Conditions on the permit, which may affect how the specimens collected under the permit may be used or distributed.
**permitRemarks**:  Any additional comments pertaining to the permit.
**permitLink**: The link to an electronic version of the permit.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed to adopt with name change to consent.

**Comment by AaronWilton** [comment]
done

**Comment by AaronWilton** [comment]
Suggestion to rename these concepts  - see issue #95
