### ISSUE TITLE
Improve definition of taxonRemarks

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#110]
Current definition:  **none**

> DWC: Comments or notes about the taxon or name.

**proposal:**
<skos:definition xml:lang="en">A comment or note about the taxon or name./skos:definition
<skos:note xml:lang="en">This differs from identificationRemarks which are additional comments made about the identification./skos:note

**Comment by nielsklazenga** [comment]
+1

**Comment by acvaughan** [comment]
+1

**Comment by nielsklazenga** [comment]
HISCOM 2016: agreed

**Comment by AaronWilton** [comment]
added
