### ISSUE TITLE
improve definitions for Assocation Type Vocabulary

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#111]
All concepts in this vocabulary only have the identifier as the description:
Based on issue #33  i have cobbled the following together

_proposed definitions_
host:  the organism with which a parasite or commensal organism lives
growingOn:  the organism upon which the specimen was growing at time of collection, particularly for  non-parasitic taxa  (e.g., epiphytes)
growingWith:  other species that were observed to be growing with the specimen at the time of collection
mixedWith:  other taxa that were collected as part of the same gathering, and form part of the same specimen (esp. cryptogams)

**Comment by afuchs1** [comment]
checked with Maggie and she is happy with this list.

**Comment by nielsklazenga** [comment]
HISCOM 2016: agreed

**Comment by AaronWilton** [comment]
done
