### ISSUE TITLE
improve descriptions of Elevation method vocabulary

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#112]
All concepts in this vocabulary have the titles as the descriptions

_proposed descriptions_
altimeter:  elevation determined using altimeter ?[at time of collection]
DEM:  elevation determined using digital elevation model
GPS:  elevation determined using GPS  ?[at time of collection]
field estimate:  elevation estimated by recorder in the field
map:  elevation estimated using a map
unknown: method of determining elevation is unknown.

**Comment by acvaughan** [comment]
I agree that describing things in full is good, even if they're mostly self-evident.

**Comment by nielsklazenga** [comment]
HISCOM 2016: agreed

**Comment by AaronWilton** [comment]
done
