### ISSUE TITLE
standardise/improve descriptions for Subject Category Vocabulary

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#116]
All concepts have the description = concept title except for ex situ.

ex situ:  image depicts subject in staged setting outside of place where it was growing

should we follow that pattern?

illustration:  image depicts an illustration
painting:  image depicts a painting
drawing:  image depicts a  drawing
in situ: image shows subject where it was growing or located
laboratory:  image shows subject in laboratory setting
cultivation:  image shows subject in culture or cultivation
label:  image shows the specimen label(s)
insect damage:  image shows insect damage to the collection object
annotation:  image shows annotations on the specimens
field description:  image shows a field description
specimen:  image shows the **whole**? specimen
fragment packet:  image shows the contents of a fragment packet
habit:  image shows the habit of the specimen
habitat:  image shows the habitat of the specimen
anatomy:  image shows anatomical detail
morphology:  image shows morphological detail
pollen:  image shows details of pollen
seed:  image shows details of seed(s)
spore print:  image shows a spore print
fruit:  image shows fruit
chromosome:  image shows details from a chromosome preparation
reproductive biology:  image shows details relating to reproductive biology

**Comment by acvaughan** [comment]
This looks good to me.

**Comment by nielsklazenga** [comment]
HISCOM 2016 decided to adopt this vocabulary.

**Comment by AaronWilton** [comment]
Agreed HISCOM 2016

**Comment by AaronWilton** [comment]
done
