### ISSUE TITLE
associatedSequences scope

### ISSUE THREAD

**Issue by GillBrown** [hiscom/hispid#126]
In the Scope/usage we say that this if for GenBank numbers but perhaps we should make this broader, given people now lodge with BOLD, etc. 

Suggest reword of Scope/usage "Use genetic data repository number. e.g Genbank accession numbers"

**Comment by nielsklazenga** [comment]
+1

**Comment by AaronWilton** [comment]
+1

**Comment by acvaughan** [comment]
+1
