### ISSUE TITLE
Geocode source

### ISSUE THREAD

**Issue by acvaughan** [hiscom/hispid#13]
This is a mixed concept and only partly corresponds with abcd:CoordinateMethod. There is no ABCD concept to deal with the first two items in the HISPID vocabulary ('collector' and 'compiler'), but there is one in Darwin Core: dwc:georeferencedBy. This element should be added to ABCD as well. A person’s name might be more useful than just 'collector' or 'compiler', but would probably have to be translated back in AVH for privacy reasons. (From the minutes of the 2012 HISCOM meeting: http://hiscom.rbg.vic.gov.au/wiki/HISCOM_2012_AGM_Canberra_minutes#11._HISPID.)

**Comment by acvaughan** [comment]
The thing about privacy was in the minutes of the meeting, but I can't actually see that it's a real issue. Perhaps it's worth asking the herbarium curators if they care if they're associated with being at work on a particular day? Or perhaps the concern is more about being associated with georeferencing errors, rather than with being at work?

**Comment by nielsklazenga** [comment]
The solution I suggested in my first comment works regardless of whether privacy is an issue or not. We don't have to say in HISPID whether providers should deliver a person's name or an institution name; providers can decide that for themselves. I wonder how useful it would be to know who exactly did the georeference when it was done by a data entry person. Most providers won't even be able to provide that information, but they will be able to tell when it was done at their institution, or, in case of an exchange specimen, at the institution the specimen originated from.

**Comment by nielsklazenga** [comment]
I think the mapping of the HISPID _Geocode source_ to the ABCD _CoordinateMethod_, from which it automatically maps to the Darwin Core _georeferenceProtocol_, was unfortunate. We should consider, after splitting off the _georeferencedBy_ values, to drop the rest of the vocabulary and provide more detailed information under the dwc:_georeferenceSources_ term (which was already available in HISPID 5).

From HISPID 5 schema:
    <xs:element name="CoordinateMethod" type="hispid:CoordinateMethodEnum" minOccurs="0">
        <xs:annotation>
            <xs:documentation>Coordinates measuring system e.g. GPS, field map reference, 
			    inferred map reference. Equivalent to "GeoreferenceProtocol" 
				in DwC Geospatial Extension 1.4.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="GeoreferenceSources" type="xs:string" minOccurs="0">
        <xs:annotation>
            <xs:documentation>[DwC Geospatial Extension v. 1.4:] A list of maps, gazetteers 
			    or other resources used to georeference the locality. The content of this 
				concept is meant to be specific enough to allow anyone in the future to use 
				the same resource to georeference the same locality. Example: "USGS 1:24000 
				Florence Montana Quad".</xs:documentation>
        </xs:annotation>
    </xs:element>

**Comment by nielsklazenga** [comment]
"I think for individual collections databases it is better to have the names, but for AVH the collector/curator distinction is more useful. However, the definition of the Darwin Core term says 'A list (concatenated and separated) of names of people, groups, or organizations', so I think it would be best to give the name(s) of the collector(s) when the record has been georeferenced by the collector (no privacy issues there) and the name of the institution when the record has been georeferenced by the curator; for exchange specimens it could be the name of the donor institution."

Hobart, 2015-10-20:
Agreed
