### ISSUE TITLE
locality and verbatimLocality

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#134]
At the HISPID Review workshop we added `verbatimLocality` (at Aaron's suggestion). We added a usage note 'Locality should always be delivered; only deliver verbatimLocality if stored separately from the locality' in the terms document. I think we should turn this around and always deliver `verbatimLocality` and only deliver `locality` if we have inferred a named locality from it. I think this is more in the spirit of Darwin Core and it is what AppleCore recommends for herbarium data.

I have already changed this for the AVH delivery, as it resolves an issue with the downloads. ALA can't handle with our often very long "locality names" in the `locality` field. There will not be the same problem in the `verbatimLocality` field. Aaron is already delivering `verbatimLocality` for the New Zealand herbaria and that ends up in the downloads.

I don't think this is a change in definition, so we can just action it, if people agree.

**Comment by afuchs1** [comment]
Neils, 
just clarifying that we agreed that verbatimLocality should be supplied as the Collectors locality with basic corrections? Rather than 'verbatim' what was written so there is not a disparity between the data in verbatimLocality and Locality.

**Comment by nielsklazenga** [comment]
Yes, the first one.

What I was saying is that we are already delivering the right data only we have been calling it the wrong name (in Darwin Core). Australian herbaria deliver `abcd:LocalityText`, which, come to think of it, maps more logically to `verbatimLocality` than to `locality`. If you do a download from the [avh-test](http://avh-test.ala.org.au) site, you'll see that New Zealand herbaria already deliver `dwc:verbatimLocality`.

**Comment by afuchs1** [comment]
so +1

**Comment by AaronWilton** [comment]
+1

**Comment by nielsklazenga** [comment]
How about:

```xml
<rdf:Description rdf:about="http://rs.tdwg.org/dwc/terms/locality">
    <rdfs:label xml:lang="en">Locality</rdfs:label>
    <rdf:type rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"/>
    <skos:definition xml:lang="en">The specific description of the place.</skos:definition>
    <dwcattributes:status>recommended</dwcattributes:status>
    <rdfs:isDefinedBy rdf:resource="http://rs.tdwg.org/dwc/terms/"/>
    <dwcattributes:abcdEquivalence>//Unit/Gathering/LocalityText</dwcattributes:abcdEquivalence>
    <dcterms:replaces rdf:resource="http://hiscom.chah.org.au/hispid/terms/loc-hispid5"/>
    <skos:scopeNote xml:lang="en">Less specific geographic information can be provided in 
        other geographic terms (higherGeography, continent, country, stateProvince, county, 
        municipality, waterBody, island, islandGroup). This term may contain information modified 
        from the original to correct perceived errors or standardize the description.</skos:scopeNote>
    <dwcattributes:organizedInClass rdf:resource="http://purl.org/dc/terms/Location"/>
</rdf:Description>
<rdf:Description rdf:about="http://rs.tdwg.org/dwc/terms/verbatimLocality">
    <rdfs:label xml:lang="en">Verbatim Locality</rdfs:label>
    <rdf:type rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"/>
    <skos:definition xml:lang="en">Description of the locality from where the specimen was 
        collected.</skos:definition>
    <dwcattributes:status>recommended</dwcattributes:status>
    <rdfs:isDefinedBy rdf:resource="http://rs.tdwg.org/dwc/terms/"/>
    <dwcattributes:abcdEquivalence>//Unit/Gathering/LocalityText</dwcattributes:abcdEquivalence>
    <dcterms:replaces rdf:resource="http://hiscom.chah.org.au/hispid/terms/loc-hispid5"/>
    <skos:scopeNote xml:lang="en">verbatimLocality should always be delivered; locality only 
        needs to be delivered if it is stored separately in the database.</skos:scopeNote>
    <dwcattributes:organizedInClass rdf:resource="http://purl.org/dc/terms/Location"/>
</rdf:Description>
```

**Comment by nielsklazenga** [comment]
I thought `verbatimLocality` could do with a better usage note:

>verbatimLocality generally is the locality information exactly as provided by the collector (or an old label), but we take it to be the locality as defined in previous iterations of HISPID, which is very nearly the same. Less specific geographic information can be included under this term if it concerns non-standard and/or historic names, for example 'Nova Hollandia', 'Van Diemen's Land'.

Already committed, but happy to change if there are suggestions.
