### ISSUE TITLE
Substrate

### ISSUE THREAD

**Issue by acvaughan** [hiscom/hispid#14]
The current definition of substrate is ambiguous. It seems to refer more to the underlying geology of the collecting locality, than to what the specimen itself was growing on. At MEL, substrate has primarily been used to record microhabitat (it has mostly been used for cryptogams). MEL has recently added a separate field for geological substrate (i.e. the HISPID concept), and would like to be able to deliver both concepts. (From the minutes of the 2012 HISCOM meeting: http://hiscom.rbg.vic.gov.au/wiki/HISCOM_2012_AGM_Canberra_minutes#11._HISPID.)

HISPID definition: http://hiscom.rbg.vic.gov.au/wiki/HISPID_3#Substrate_.28sub.29

**Comment by nielsklazenga** [comment]
There is a concept for this in the Environment Ontology (ENVO), 'environmental material' (http://purl.obolibrary.org/obo/ENVO_00000154), which has been suggested should be in Darwin Core as _environmentalMaterial_, but the vocabulary on it is inadequate (no 'bark', 'tree trunk' or 'rotten log', just 'wood'). I think the concept is just slightly different.

**Comment by acvaughan** [comment]
I just found some additional notes about substrate (from an ALA/AVH user):
* it can be critical for identification for mycologists and entomologists
* would be good to have a wider working group looking at a vocabulary for it (not just HISCOM)
* vocabulary would be useful internationally

**Comment by nielsklazenga** [comment]
Substrate information can be quite important, but that only means that it needs to be there, which it already is in _habitat_. A separate substrate field would be useful if it had some sort of controlled vocabulary on it and if it – not the field, but the data in it – would be available for all records for which it is relevant. A single herbarium delivering it for only new records won't do, but that is all that is going to be achieved by adding a substrate term to HISPID. The same goes for all other habitat terms mentioned in issue #23. In order for these fields to be useful there needs to be a plan to populate these fields for all records (where relevant), perhaps through a combination of data mining and crowd sourcing. We can't rely on the routine databasing at herbaria, as there is not going to be another AVH databasing project, and we should see the data in these fields not as primary data, but as interpreted data.

**Comment by ben3000** [comment]
+1, with clear names for each, so that we can easily explain the difference.

**Comment by nielsklazenga** [comment]
Also for after ratification. Let's see if we can find someone (from outside HISCOM perhaps) to drive this.

**Comment by nielsklazenga** [comment]
Since this is a new term and we intend to have a vocabulary, I propose to prevent it from being used as a free text field by using `rdfs:range` to indicate that it can't be a literal. We should look into using `rdf:range` for all fields that have a vocabulary on it.
