### ISSUE TITLE
Identification verification status and identification references

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#16]
The dwc:_identificationVerificationStatus_ element was adopted without change from HISPID, where it is called 'Verification level flag'. I don't think it is used very often though and no Australian herbarium delivers it to AVH. The concept could be useful though, which is why it is in Darwin Core I imagine, so I would like to see if we can salvage it for HISPID.

I don't think the vocabulary on the element is particularly useful, or rather bordering on meaningless and misleading. As someone who has spent fifteen years of his life cleaning up after "taxonomists and other competent persons" I know that it doesn't mean anything if an identification is done by "a taxonomist or other competent persons". I also know that when I am engaged in a taxonomic revision of a group – which is when any identification by me of a specimen will get the highest verification level flag, safe if the specimen belongs to the type material of a name – my identifications are actually not that good. Once I am not any more, it is a different matter, but by then I am just a "taxonomist or other competent person" (and even that is in the eyes of the beholder). The Darwin Core definition says that _identificationVerificationStatus_ is a 'categorical indicator', but using the numbered categories in HISPID (which DwC gives as examples) makes it appear ordinal, rather than merely categorical.

Futhermore, I think that the current vocabulary makes _identificationVerificationStatus_ a mixed concept, as it combines the effort that went into the identification with the putative expertise of the identifier. I think the element should only be about the former; the latter is more than sufficiently covered by the _identifiedBy_ element.

When I started collecting again in 2012, I adopted the practice of putting a note 'field det.' with all my identifications (this information is delivered to AVH in the _identificationRemarks_ element). Ninety per cent or more of those identifications I consider reliable, although I would still check many of them microscopically, if only I had the time. I also don't have time to properly identify the other 10 per cent, so what I do is database all these specimens and have them incorporated in the MEL collection. If I then feel the need (or have the time) to re-identify the specimen, I just put a new identification in (which would be a 'conf.' if I got it right the first time and otherwise a 'det.'). Or maybe someone else will. I have myself identified way more collections from other people than my own.

I have recommended some of our other botanists (only one actually) to adopt the same practice, just to get through the backlog, and I think more of our botanists would use it if there were a dedicated field for it. ... and I think _identificationVerificationStatus_ might be it.

So, for the vocabulary I have something like this in mind:
* field identification
* microscopic identification/confirmation
* identification using relevant literature
* compared with reference specimens
* ...

Not all the terms will be relevant to all groups. Therefore, I suggest not numbering them like the current vocabulary, thereby making it appear ordinal. I also think words are more useful to users than numbers.

In combination with the third term in the list, I would like to draw attention to the Darwin Core term _identificationReferences_. It's not in HISPID I think, but I would like to include it. It might not get used for most identifications, but I think some of our botanists here at MEL would use it, as I see them appear in the _identificationRemarks_.

We also need to consider the use of the HISPID _determinavit_ (ABCD:_IdentifierRole_) in this context. There is no equivalent in Darwin Core for this element, but some term in its vocabulary go to identification status. Maybe just include:
* temporary sorting slip
* confirmed

in the vocabulary for the _identificationVerificationStatus_ element?

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Need to separate between identification confidence, which current vocabulary more or less refers to and identification verification status. Identification verification status should only kick in when an assertion has been made that the identification might be wrong, for example a dot on a map in the wrong spot.

Share vocabulary with georeferenceVerificationStatus; add 'Verified by specialist in group' as subclass of 'Verified'.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:
Description; "An indicator of the extent to which the taxonomic identification has been verified to be correct."

**Comment by AaronWilton** [comment]
updated definition and vocabulary
