### ISSUE TITLE
Life form

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#17]
The _habit/life form_ element in HISPID is a free text field. We've got it in our collections database at MEL for as long as I can remember, but over the years the content gradually regressed to a general description, so after the migration we called it 'descriptive notes'. I think having the field is an abomination, but people won't let me get rid of it. The consequence of putting descriptive notes in a field of their own rather than in collecting notes or identification notes where they should be is that they can't be mapped onto _occurrenceRemarks_ or _identificationRemarks_, because we don't know which of these they are, and can only be delivered as miscellaneous notes – along with quarantine notes etc. – which makes it highly unlikely that any AVH user will ever get to see them (let alone knows who they are coming from). But I'm wandering off...

I think having a life form field in AVH, where people can search and facet on and maybe even get a pie chart for, would be very useful for AVH users. However, as a free text field the concept is less than useless and its contents would be better off in collecting notes or identification remarks.

According to HISPID 3 'there are no universally accepted schemes for the classification of habit that modern collectors can be expected to follow'. That may be true, but the requirements on our data are different now and there are definitely systems that can be consistently employed and would add extra value for AVH users. And I think we don't need to get this information from the collectors, just like we don't expect collectors to tell us that a plant has flowers. All information about the plant itself that we get from collectors is best placed in `occurrenceRemarks` or `fieldNotes` (which we don't use yet).

For vascular plants there is the Raunkiaer (1934) system of life forms – pretty universally accepted if you ask me – which in slightly modified form is used in Kew's Seed Information Database (http://data.kew.org/sid/plantform.html; below is the Kew implementation):

* __Phanerophytes (phan.)__ have stems that are woody and persistent, and buds that are normally exposed 3 m or more above ground level. This category includes trees and large shrubs
* __Nanophanerophytes (nanophan.)__ also have woody, persistent stems, but are lower in stature with buds typically located between 0.5 m and 3 m above ground level. This category includes smaller shrubs.
* __Herbaceous phanerophytes (herb. phan.)__ have herbaceous stems that persist for several years and include tropical species such as bananas and plantains.
* __Chamaephytes (cham.)__ can have stems that are herbaceous or woody and persistent, and have buds that are located above soil level, but never by more than 50 cm. This group includes dwarf shrubs and some perennial herbs.
* __Hemicryptophytes (hemicr.)__ have herbaceous stems that often die-back during unfavourable seasons, and surviving buds placed on (or just below) soil level. This group includes many biennial and perennial herbs, including those in which buds grow from a basal rosette.
* __Geophytes (not abbreviated)__ have stems that die back during unfavourable seasons, with the plant surviving as a bulb, rhizome, tuber or root bud.
* __Therophytes (ther.)__ complete their entire life-cycle during the favourable season, and survive the unfavourable season as a seed. This group includes all annual herbs.
* __Epiphytes (epi.)__ grow on other plants (their growing buds occur on another plant).
* __Helophytes (hel.)__ are plants in which surviving buds are buried in water-saturated soil, or below water-level, but that have flowers and leaves that are fully emergent during the growing season. The group includes many marsh and emergent aquatic herbs.
* __Hydrophytes (hydro.)__ are fully aquatic herbs in which surviving buds are submerged, or buried in soil beneath water. Their stems and vegetative shoots grow entirely underwater and leaves can be submerged or floating, but only the flower-bearing parts may be emergent.

The GBIF _Life Form_ vocabulary (http://rs.gbif.org/vocabulary/gbif/life_form.xml) uses a subset of this system:
* __Phanerophyte (P)__ Projecting into the air on stems – normally woody perennials - with resting buds more than 25 cms above soil level, e.g. trees and shrubs. May be further subdivided according to plant height in __megaphanerophytes__, __mesophanerophytes__ and __nanophanerophytes__ and other characters, such as duration of leaves (evergreen or deciduous), presence of covering bracts on buds, succulence and epiphytism.
* __Chamaephyte (C)__ Buds on persistent shoots near the ground – woody plants with perennating buds borne close to the ground, no more than 25 cms above soil surface, e.g. bilberry and periwinkle.
* __Hemicryptophyte (H)__ Buds at or near the soil surface , e.g. daisy, dandelion, crocus.
* __Cryptophyte (K)__ Below ground or under water - with resting buds lying either beneath the surface of the ground as a rhizome, bulb, corm, etc., or a resting bud submerged under water. Cryptophytes are sometimes divided into subgroups, e.g. __Geo-,__ __Helo-__ or __Hydrophytes__,
* __Therophyte (T)__ Annual plants which survive the unfavourable season in the form of seeds and completes its life-cycle during favourable seasons. Annual species are therophytes. Many desert plants are by necessity therophytes.
* __Epiphyte (E)__ See Phanerophyte above.

For bryophytes we've got the Mägdefrau (1982) classification of bryophyte life forms (lifted from http://www.bryoecol.mtu.edu/chapters/4-5AdaptStratForm.pdf; that's a really good read, by the way, if bryophytes is your kind of thing):
* __Annuals__  – pioneers; no vegetative shoots remain to carry on a
second year; _Buxbaumia_, _Diphyscium_, _Ephemerum_, _Phascum_, _Riccia_
* __Short turfs__  – open mineral soils and rocks; regenerative shoots;
form spreading turfs for only a few years; _Barbula_,
_Ceratodon_, _Didymodon_, _Marsupella_
* __Tall Turfs__ – forest floors in temperate zones; can conduct water
internally; very tall; persist by regenerative shoots;
Bartramiaceae, Dicranaceae, Polytrichaceae,
_Drepanocladus_, _Herbertus_, _Sphagnum_, _Tomenthypnum_
* __Cushions__ – rocks, bark, Arctic, Antarctic, alpine; usually high light;
grow upward and sideways; hemispherical; persistent for many
years; _Andreaea_, _Grimmia_, _Leucobryum_,
_Orthotrichum_, _Plagiopus_, no liverworts
* __Mats__ – rocks, bark, [on leaves (epiphyllous) in tropics];
plagiotropic and persistent for a number of years; Lejeuneaceae,
most Marchantiaceae, _Homalothecium_, _Lophocolea_,
_Plagiothecium_, _Radula_
* __Wefts__ – forest floor of temperate zone; hold considerable capillary
water; grow loosely and easy to remove from substrate; new layer
grows each year; Brachytheciaceae, Hylocomiaceae,
_Bazzania_, _Ptilidium_, _Thuidium_, _Trichocolea_
* __Pendants__ – epiphytes, especially in tropical cloud forests; long
main stem with short side branches; Meteoriaceae,
Phyllogoniaceae, some tropical _Frullania_
* __Tails__ – on trees and rocks, shade-loving; radially leafed, creeping,
shoots stand away from substrate; _Cyathophorum_, _Leucodon_, _Spiridens_, some tropical _Plagiochila_
* __Fans__ – on vertical substrate, usually where there is lots of rain;
creeping, with branches in one plane and leaves usually flat;
Neckeraceae, Pterobryaceae, _Thamnobryum_,
some _Plagiochila_
* __Dendroids__ – on ground, usually moist; main stem with tuft of
branches at top; _Climacium_, _Hypnodendron_, _Hypopterygium_,
_Leucolepis_, _Pleuroziopsis_, _Symphogyna
hymenophyllum_
* __Streamer__ – long, floating stems in streams and lakes; _Fontinalis_

These are useful terms, which I use in my descriptions.

Mycologists might want to use their morphotypes (mushroom, truffle, puffball, bract etc.) although these might be better placed in the _Species group_ (our _Botanical group_) or _Species subgroup_ facet, while for lichens I can think of crustose, thallose, foliose, fruticose, etc. lichens. There will be systems for freshwater and marine algae too.

I think many of these life forms will show interesting biogeographical patterns, so it will be useful to have them in AVH and ALA. Dendroid bryophytes for instance are a typical component of our wet forests for example, but in the Northern Hemisphere they are very rare. Puffballs are very well represented in Australia's interior.

As life form shows very strong correlation with taxonomy as well, I do not propose that this information is delivered with herbarium data, but rather with the species lists. That is also how MSB and GBIF (http://rs.gbif.org/terms/1.0/lifeForm is part of the http://rs.gbif.org/extension/gbif/1.0/speciesprofile.xml extension) are using it. I would like to add the bryophyte life forms to AusMoss and know that Tom would like to have them in AusFungi (well, not the bryophyte ones of course, but you know what I mean). So maybe the element I am suggesting has got nothing to do with HISPID, but it means that, if herbaria want to deliver this information to AVH, they can't do it in the _habit/life form_ element.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20: Create better definition (change 'description' to 'list of terms').

Description: "A controlled vocabulary term describing the habit or life form of the specimen on which the collection object is based."

Comment: "We intend to provide a controlled vocabulary, and/or a term to identify a controlled vocabulary."

**Comment by nielsklazenga** [comment]
http://rs.gbif.org/terms/1.0/lifeForm

**Comment by AaronWilton** [comment]
Definition does not match the above text
