### ISSUE TITLE
Life stage

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#18]
_lifeStage_ is a Darwin Core element that we don't have in HISPID yet. The BioCache has a 'Life stage' facet, which we don't use in AVH, as for AVH data the facet includes terms from the Phenology field (which is now delivered as _reproductiveCondition_) as well as a lot of junk.

I have just added _lifeStage_ to the AVH delivery, as a data set from the Janet Cosh Herbarium (WOLL), Wollongong University, that has just been added to AVH had a Seedling column (with values 'true' or 'false'), besides Flowers, Fruit, Buds etc. columns. While Flowers, Fruit and Buds could be accommodated in the _reproductiveCondition_ field, Seedling is really a _lifeStage_ and I didn't want to lose the information. The – now five year old – MEL Collections Development Policy speaks of the development of a seedling collection – not sure if we have it already; it is not in the database – so we will have a use for the field as well.

Therefore, I would like to add _lifeStage_ to HISPID. A vocabulary on the _lifeStage_ element should probably have more terms than only 'seedling', but for now that is enough for me. Other herbarium databases may already record other information that can be accommodated here. For Fungi, for example, I could think of 'anamorph' and 'teleomorph' (not 100 per cent sure if these are really life stages, but I think so). ~~The 'gametophyte' and 'sporophyte' terms in the _reproductiveCondition_ (_Phenology_; #12) vocabulary are more appropriately placed in a _lifeStage_ vocabulary, but are not very useful to record, as all collections of land plants always belong to the same generation (depending on the group) or contain both generations (bryophytes with sporogones; ferns with prothallia), so it is more useful to record the presence of the structures that are not always there.~~

**Comment by AaronWilton** [comment]
I agree that this is worth adding and that some of terms in *reproductiveCondidtion* need moved to this field.

**Comment by nielsklazenga** [comment]
Contra my own note on 17 January, 'gametophyte' and 'sporophyte' are not life stages. Any one organism at any one time (that's an _Occurrence_) can only have one _lifeStage_. Any plant will have both sporophyte(s) and gametophyte(s) in part of its life cycle.

**Comment by AaronWilton** [comment]
HISCOM 2015 - Vocabulary needed

**Comment by nielsklazenga** [comment]
HISCOM, 2015-10-22:
Add botanical terms from [GBIF vocabulary](http://rs.gbif.org/vocabulary/gbif/life_stage.xml).

**Comment by ben3000** [comment]
Completed aside from consideration of `reproductiveCondition`.

**Comment by nielsklazenga** [comment]
We were only going to adopt the botanical terms from the GBIF vocabulary, not the whole vocabulary. I propose to remove 'larva' and 'pupa' and put 'seedling' back in as a subclass of 'juvenile'.

**Comment by AaronWilton** [comment]
* URIs - agree - done
* seedling is an alternative title of juvenile in the GBIF vocabulary  so nothing needs to be done.
* removed pupa, larva

**Comment by nielsklazenga** [comment]
Only in HISPID 'seedling', rather than 'juvenile' should be the preferred label. I would rather throw out 'juvenile' altogether, as it is not used in botany. I don't consider the two terms synonymous.

**Comment by AaronWilton** [comment]
hmmm - not sure that is true - juvenile is used for heteroblastic species

**Comment by nielsklazenga** [comment]
So we agree that it is not the same as __seedling__.

**Comment by nielsklazenga** [comment]
Also, "juvenile" in "juvenile leaves" as used in heteroblastic species is not of `lifeStage`.

**Comment by AaronWilton** [comment]
have put juvenile into hispid name space since definition (via alternative) differ from GBIF usage.

**Comment by nielsklazenga** [comment]
Good one. In the SKOS example in #97 I placed all terms in a new namespace (as the GBIF terms are not SKOS concepts). I think we should have a separate namespaces for terms and vocabularies (eventually).
