### ISSUE TITLE
Georeference verification status

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#19]
_georeferenceVerificationStatus_ is a Darwin Core field that we don't have in HISPID yet (or rather it is not defined, but it is in the ABCD 2.06b and HISPID 5 schemas).

At MEL we have implemented _georeferenceVerificationStatus_ with the following vocabulary:
* requires verification
* verified by collector
* verified by curator.

These terms are the examples given in the Darwin Core documentation.

We populate the field based on the quality tests by ALA. MEL records that fail the "Coordinates don't match supplied country" or "Coordinates don't match supplied state", or are outliers for one or more layers will get the value 'requires verification' in the _georeferenceVerificationStatus_ field. This is for our own use only and will not be delivered back to AVH. Only when the georeference is verified and the  value changed to 'verified by curator' does it get delivered back to AVH. We might want to add a term 'corrected by curator' for when we have to fix the georeference, but we haven't thought that far yet.

**Comment by nielsklazenga** [comment]
The Apiary vocabulary for this element is at http://www.apiaryproject.org/sites/default/files/georeferenceVerificationStatusVocab.xsd.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Add to vocabulary: 'Verified by collector', 'Verified by custodian', 'Verified by contributor'. Need to add descriptions of vocabulary items. Newly added items are subclasses of 'verified'.
Fix description: "A categorical description of the extent to which the georeference has been verified to represent the best possible spatial description."

**Comment by AaronWilton** [comment]
* Added terms & description
* Added an attribute parentConcept to the vocabulary concepts (will open a related issue for discussion)
