### ISSUE TITLE
GUIDs

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#2]
We have already decided that we should have GUIDs for specimen records (which would be delivered as _occurrenceID_).

We, MEL, also already deliver _identificationID_. Our _eventID_ is probably not so useful at the moment, as in our database we have a one-to-one relationship between _Collection Object_ and _Collecting Event_ (not in the database actually, but enforced by the way we've set up our forms), but once our multisheets and mixed collections have been sorted out we could deliver those as well.

The Dublin Core _identifier_ is a required element in Audubon Core, so herbaria that want to deliver images need to be able to deliver an '_imageID_' too.

So, the proposal is to add the following four GUIDs:
* _occurrenceID_
* _eventID_
* _identificationID_
* '_imageID_' (dcterms:identifier in Audubon Core; if we are going to include image metadata)

**Comment by ben3000** [comment]
The last time we cast around for information about what each herbarium was doing is currently listed at http://hiscom.rbg.vic.gov.au/wiki/Units_and_their_IDs, which may no longer be correct, but it will serve as a handy guide.

**Comment by ben3000** [comment]
What is the name given to the unique id of a part of a specimen that was separated during specimen processing and placed on a separate sheet so that it can be stored under different conditions (e.g. a different room)?

Each of them should have received the same unique id before separation, but then receive this "part-of-specimen" unique id when/if separated into physical parts.

**Comment by nielsklazenga** [comment]
That depends on the herbarium, see the [Units and their IDs](http://hiscom.rbg.vic.gov.au/wiki/index.php/Units_and_their_IDs) page on the HISCOM Wiki. We give a unique(-ish) catalogue number to each individual sheet or part. I would prefer your solution, but it is not that easy to change a practice that has been employed for over thirty years.

**Comment by AaronWilton** [comment]
Implemented
