### ISSUE TITLE
Associated taxa

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#20]
The HISPID _Associated species_ concept is currently mapped, via the ABCD/HISPID 5 _SynecologyComments_ to the Darwin Core _associatedTaxa_. Seems pretty straightforward, right?

Wrong. The HISPID element is free text, while the Darwin Core term is a list of key–value pairs with the key being the association and the value the identifier or the name of a taxon. Also, the definition of the Darwin Core concept is much wider than that of the HISPID concept, if it includes the HISPID concept at all.

At MEL we have always had a 'host' field in our collections database. We could never deliver that in HISPID, but now in Darwin Core we can (and do). We do have some difference of opinion among our botanists to what sort of associations the term 'host' should apply – for me the term only applies to parasitic or symbiotic relationships, while for others it also applies to epiphytes (the host being the taxon they grow on) – but I think this is unproblematic, as from the context it will always be clear what is meant, and I would be happy to use the more inclusive concept (even if I haven't so far).

An 'Associated taxa' field (in the HISPID sense) we have only had since our migration. We deliver that also under the _associatedTaxa_ with the key 'cohabitatants' (Alison and I brainstormed long and hard for that). Having the field might have been my idea, but now I wouldn't use the field any more (people who never change their mind just don't think enough). For me just growing in the vicinity doesn't qualify as association. With the group of plants that I collect an additional consideration is that even if I would use 'associated species' in the HISPID sense, I would only list taxa in the same synusium, so other bryophytes and lichens (except that I couldn't list those, as I don't know them). Species that make up the vegetation (if I know them, or have someone with me who can tell me) I would already list in the (verbatim) _habitat_ field. I realise that it might be different for people working on vascular plants, which are among the taxa that make up the vegetation, and for which vegetation is also more important (there is not a single species of bryophyte, for example, that is unique to cool temperate rainforest; all "rainforest bryophytes" also grow in wet sclerophyll forest; microhabitat and microclimate are much more important for bryophytes than vegetation).

While I probably wouldn't use the field myself, I don't mind if other people do want to use it, and I will deliver it. However, if people want to use it, we would need some stronger terms than merely 'associated species' as keys. So maybe use phytosociological terms like 'defining taxa' and 'differentiating taxa' (I actually don't know the English terms; this is my best translation from Dutch) or maybe the Tansley abundance values, like 'dominant', 'co-dominant' or 'abundant'. Also, at least in theory we would like to be able to resolve and match the associated taxa, so people can query on them, so they would have to be real names of taxa. The lists that are currently delivered in the 'associated species' field should be delivered as part of _habitat_ (that's my opinion, not a command).

**Comment by AaronWilton** [comment]
Inclusion of associatedTaxa (we called this associatedSpecies in the Review) as well as associatedTaxon and associatedType.

Question:  do we need all 3 fields?  (as currently in HISPID2015.xlsx)
Can we not have just  2 and indicate that when mapping to DWC they will be included in the same associatedTaxa (this is what i thought we had agreed at the workshop).

**Comment by nielsklazenga** [comment]
I think we need only two fields, `associatedTaxa` and `associationType`. We don't need `associatedTaxon`, as we can say that in the HISPID implementation `associatedTaxa` is a list of key–value pairs (as in Darwin Core) where the key is a `hispid:associationType` and the value a `dwc:scientificName`.

(We are not mapping to Darwin Core; we are basing HISPID on Darwin Core)

**Comment by nielsklazenga** [comment]
Please note that the concept as we have defined it here cannot be delivered in core ABCD.

**Comment by nielsklazenga** [comment]
Done...
