### ISSUE TITLE
Island, island group and water body

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#21]
_island_, _islandGroup_ and _waterBody_ are three Darwin Core elements that we don't use yet, but could be very useful. I would like to see them added to HISPID and be able to deliver them to AVH.

Our localities are long strings that can't be indexed, and hence not queried on by AVH users. We have had many complaints about that. The more information we can split off into queryable fields, the better. We have actually had a request for an island facet, which we discussed in HISCOM. HISCOM rather typically decided that ALA should take care of it based on the georeference, which ALA still has to agree to (and Nick wasn't too keen). However, this solution might solve the immediate issue in AVH, but would only take care of a handful of Australian and New Zealand islands and there are islands in other parts of the world for which we have data as well. I have collected on seven or eight islands in South America (and on a big one in Malesia) and I know that especially CANB and NSW have many collections from the Malesian region, which is almost completely made up of islands. Our data goes to GBIF too and especially there it is important that we are Darwin Core compliant and not do our own thing.

I actually think having these fields will make databasing easier. I also think that getting the data out of our existing data won't be too big a deal (if it were we couldn't expect ALA to do it either), as it wouldn't be a problem if the islands (etc.) stayed in the locality string as well. It will also probably not concern huge amounts of records. And some herbaria might already have the fields in their database, but are just not able to deliver it because the fieds are not in HISPID.

We have an immediate use for _island_ and _islandGroup_. _waterBody_ I just picked up because it is in Darwin Core. Our database out of the box also has a 'National park' field (which we haven't implemented, or use for something else), which I think would be useful as well, but it is not in Darwin Core, so I am not proposing it at this stage.

**Comment by nielsklazenga** [comment]
Adopted.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Comment: "This term should only be applied when it adds clarity to the location."

**Comment by AaronWilton** [comment]
Hobart 2015-10-22:  Adopted
