### ISSUE TITLE
Frequency

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#22]
Another field that is only useful if it has a vocabulary on it (not really a vocabulary actually; it can also be a number and a "unit"). If not, it is better off in _occurrenceRemarks_.

This field can be delivered in Darwin Core in future, as an _organismQuantity_ concept has just been proposed. However, this element should only be used in combination with _organismQuantityUnit_, so no free text allowed. _organismQuantityUnit_ doesn't have to be an actual unit, like 'indivuduals', but can also be a classification system. In the discussions on the TDWG list the Braun-Blanquet scale, which is often used in vegetation relevés, was mentioned. For our sort of data, I think the Tansley (1946) scale would be more appropriate:

Symbol | Abundance or frequency | Numerical transformation
----------|---------------------------------|---------------------------------
__s__ | _sparse_  | 1
__r__ | _rare_ | 2
__o__ | _occasional_ | 3
__lf__ | _local frequent_ | 4
__f__ | _frequent_ | 5
__la__ | _local abundant_ | 6
__a__ | _abundant_ | 7
__ld__ | _local dominant_ | 8
__c__ | _codominant_ | 9
__d__ | _dominant_ | 9

(from: http://nl.wikipedia.org/wiki/Vegetatieschaal_van_Tansley; original source: __Tansley, A.G. (1946)__ _Introduction to plant ecology_. Allen & Unwin, Londen.)

I would use the words, not the symbols, just because people might not be familiar with those.

**Comment by nielsklazenga** [comment]
Proposal accepted.

**Comment by AaronWilton** [comment]
I believe the proposed terms are organismQuantity and organismQuantityType.
These are currently at public comment status in TDWG, but have not been put to the EXEC and are therefore not available in the DWC name space.

What do we do about these fields in HISPID -> at the least the need a different status because the mappings to DWC and namespace are not yet available....

**Comment by AaronWilton** [comment]
Hobart 2015-10-22:  terms adopted
