### ISSUE TITLE
Vocabularies should be by agreement, not enforced by schema

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#25]
The 'should be' is just my opinion, not a command or law of nature, although I think there might have been agreement on this in an earlier HISCOM meeting.

Vocabulary restrictions by schema are problematic for data delivery, as many values will not be delivered, leading to loss of data, for example because people don't realise that XML is case-sensitive (and capitalisation in HISPID vocabularies is not consistent). Also, vocabulary restrictions by schema don't apply to CSV and hence Darwin Core Archive, so different delivery mechanisms will result in different data. Having the vocabularies in the schema also makes it harder to update vocabularies.

The vocabulary restrictions in HISPID 5 are also the cause of data delivered in HISPID 5 not being valid ABCD (or not ABCD at all).

**Comment by ben3000** [comment]
So, based on today's meeting, we store all vocabulary restrictions in the vocabulary document only?

**Comment by AaronWilton** [comment]
Yes - i think so.  But we need to resolve the linking method...

**Comment by ben3000** [comment]
I'd still find it useful to be able to create an XML Schema that used the restrictions from the vocabulary so that I could confirm that PERTH outputs were valid. How would I accomplish this without having the restrictions in the schema?

**Comment by AaronWilton** [comment]
I think should then try to use the rdf document to try and create XSD with and without the vocabulary restrictions

**Comment by ben3000** [comment]
Ah, using XSLT?

**Comment by AaronWilton** [comment]
hopefully....
