### ISSUE TITLE
Basis of record

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#27]
This has just been added as there has been some confusion in the past.

_basisOfRecord_ is the only required element in Darwin Core and is the only element that has a strong vocabulary on it. This vocabulary is more restricted than that on the ABCD term RecordBasis. RecordBasis seems a mix of _dwc:basisOfRecord_ and _dcterms:type_ (or is only _dcterms:type_), which in Darwin Core have been split.

From Darwin Core:
> Terms under the Record-level Terms section apply to the whole record regardless of the record type. For example, a record for a camera trap bird sighting would fall into the Dublin Core dcterms:type category StillImage and at the same time into the Darwin Core basisOfRecord category MachineObservation - a particular type of Occurrence, so the value of dcterms:type term for the record would be "StillImage" and the value of the basisOfRecord term would be "MachineObservation" to show which kind of Occurrence record it is. All of the rest of the record-level terms would apply to the Occurrence record.

_basisOfRecord_ for all AVH records should be _PreservedSpecimen_.

**Comment by AaronWilton** [comment]
Included dcterms:type as field in HISPID2015

**Comment by nielsklazenga** [comment]
I think we're good...
