### ISSUE TITLE
Additional collectors

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#30]
This is going to be a hard one to ditch, as there are lots of people in our community who are inordinately interested in collectors.

The problem is that in HISPID and ABCD one can distinguish between primary and additional collectors, but that Darwin Core just has the _recordedBy_ term.

The implementation of primary and additional collectors is different at different herbaria and perhaps within individual herbaria. Some herbaria very strictly have only a single primary collector and the other collectors are additional, but other herbaria – including mine – can have multiple primary collectors and the additional collectors field is used for assorted family and pets. HISPID might be considered a bit ambiguous about what to do, but does indicate that the names in the primary collector field are of the people who the collecting number belongs to, so you can only have multiple primary collectors if they share a number series. In HISPID, you are also not allowed to give collector's initials as part of the collecting number, while in Darwin Core it is recommended.

The way this data is exchanged in Darwin Core will vary according to how these fields are implemented. For MEL data, if I could only deliver _recordedBy_, I wouldn't include our additional collectors in it and would stop delivering those (I don't think that is a big loss).

There is a privacy issue with (some) additional collectors as well. We justify publishing the names of collectors with that, if you lodge a specimen, your name might get out there as the collector of that specimen. With additional collectors that expectation isn't there. They might not even know their name is on the sheet.

**Comment by AaronWilton** [comment]
Additional collectors are not the same as secondary collectors ->  expecting that we will pass all primary and secondary collectors.

**Comment by afuchs1** [comment]
Decision : continue HISPID practise to NOT include collectors initials in the collecting number

**Comment by AaronWilton** [comment]
Outcome:  those institutions with primary, secondary and additional make an internal rule that they follow
