### ISSUE TITLE
Identifier role

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#31]
Another tough one to get rid of, but not very useful and without an equivalent in Darwin Core.

**Comment by ben3000** [comment]
Do we make use of this in AVH? Seems like something our curatorial staff would find useful, but then I'm not a curation officer.

**Comment by nielsklazenga** [comment]
Yes, it is in the record detail, but not indexed. Many people would object to it being removed and almost every det. slip has it, so let's not rock the boat. It is just that the terms are overloaded and mean different things to different people and that for the terms that may be considered useful for curation that were added in HISPID 5 this was the wrong element to put them in.

**Comment by ben3000** [comment]
Keep it.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Oh, all right, we'll keep it.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Approved
