### ISSUE TITLE
Association type

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#33]
At the HISPID Review workshop earlier this week we minted the new HISPID concept __associationType__ (along with __associatedTaxon__), in order to enable mapping of the old HISPID __Associated species__ element to the Darwin Core _associatedTaxa_. The Darwin Core concept is a broader concept than the old HISPID one and requires a key to indicate the type of association as well as a value.

The vocabulary we have come up with so far is:
* host (this is an addition)
* associated with.

I am not happy with the latter term, as 'associated' can hardly be considered an association type. I propose to change that to 'growing with' (unless someone can come up with something better...). I would also like to format the terms as properties, so that they can also be used as elements by themselves if the transfer mechanism doesn't allow transfer of key–value pairs. And, just to kill an extra bird with the same stone, I would like to include a term 'mixedWith'.

So here is the vocabulary I came up with for now:
* host
* growingWith
* mixedWith.

**Comment by nielsklazenga** [comment]
__associationType__ could be put to more general use and could also be used for _associatedOccurrences_ and _associatedOrganisms_.

**Comment by AaronWilton** [comment]
Do we want to be more explicit about other types of associations (e.g., epiphytes) or leave this in the general term **growingWith**?  Maybe if we don't want to break it down in to specific types we could add **growingOn** (I think the differentiation of On and With are important).

I think we need to be clear about what these terms mean though...
Can you define when we would use mixedWith compared with growingWith?
(we need to do all for all the terms i think)

**Comment by nielsklazenga** [comment]
I agree that all vocabulary terms (not just in this vocabulary) need definitions. What I mean with _mixedWith_ is parts of mixed collections. So it is not all that different from _growingWith_, only that _mixedWith_ is stuff that ended up in the packet (in the case of mosses). Also, _growingWith_ would have to come from the collector, while _mixedWith_ can come from an identifier (only lazy collectors would use _mixedWith_).

I would love to include _growingOn_ in the vocabulary, as well as any more specific associations we can come up with. The more specific the better, I think. We can have a taxonomy that can group more specific association types into more inclusive ones.

**Comment by ben3000** [comment]
I like the distinction between **growingWith** and **growingOn**.

**Comment by nielsklazenga** [comment]
I would never have put __growingWith__ and __growingOn__ together. It is the distinction between __host__ and __growingOn__ that I like.

**Comment by ben3000** [comment]
**Host** and **growingOn**? Did you mean **host** and **growingWith**?

**Comment by nielsklazenga** [comment]
No, that is how most people use __host__.

>>> Ben Richardson <notifications@github.com> 17/03/2015 4:29 PM >>>

Host and growingOn? Did you mean host and growingWith?

**Comment by nielsklazenga** [comment]
No, that is how most people use __host__.

**Comment by ben3000** [comment]
Sorry, here's what I mean by my earlier comment: I like that there is a distinction between a host-type association and a growing-in-the-same community/soil type/location association. I'm not so picky about the name of each.

**Comment by nielsklazenga** [comment]
So you are suggesting to replace __host__ with __growingOn__?

**Comment by ben3000** [comment]
No, I don't care about the name, just that the concept is in there. **Host** is definitely more succinct.

**Comment by nielsklazenga** [comment]
Okay, but I would like both __host__ and __growingOn__, as I don't think they are the same.

**Comment by ben3000** [comment]
Ah, a nuance I hadn't considered. That's OK with me.

**Comment by AaronWilton** [comment]
A strawman: 
**host** - the host taxon for the specimen of a parasitic or pathogenic taxa
**growingOn** - the "host taxon" for a specimen of a non-parasitic plants
**growingWith** - other species that were observed to be growing with the specimen at the time of collection
**mixedWith** - other taxa that were collected as part of the same gathering, and usually part of the same specimen (esp. cryptogams)

**Comment by nielsklazenga** [comment]
Just comments because I don't have anything better right now.
* __host__ can be in mutualistic relationships, such as mycorrhiza, as well. It just suggests a closer association than just __growingOn__.
* __growingOn__ needs to have the references to host and substrate removed. A parasite or fruitbody of mycorrhizal fungus does not need to grow on the host (at least not visibly).

**Comment by ben3000** [comment]
I would make it such that *growingOn* could optionally identify the host or the substrate and thus form a link between the host and the parasite/symbiont.

**Comment by nielsklazenga** [comment]
No, not the substrate. 'Host' is an organism or taxon, while substrate is a material (bark, rock, etc.). `growingOn` is the same as `host`, but then for epiphytic, rather than parasitic relationships.

**Comment by ben3000** [comment]
Yeah, I get that. I'm just thinking aloud about the potential for generalisation. Of course it may be over-generalisation :)

**Comment by ben3000** [comment]
Why not use `parasitic`, `epiphytic` and `host` as  values to make the difference between `host` and `growingOn` clearer?

**Comment by nielsklazenga** [comment]
I edit multiple times all the time. I was wondering if that sends annoying emails every time.

This would turn the relationship around, which is not in line with Darwin Core. Also, 'parasite' and 'epiphyte' do not necessarily indicate a relationship. You can say that something is a parasite without ever referring to the host; the other way around not so much.

**Comment by nielsklazenga** [comment]
Seems that all that needed to be done has been done.
