### ISSUE TITLE
Add a status property for each term

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#36]
Terms should have a status, e.g. "current", so that it is clear whether a term is in current use, and allows us to deprecate terms in the future.

**Comment by AaronWilton** [comment]
DWC uses  dwcattributes="http://rs.tdwg.org/dwc/terms/attributes/"  dwcattributes:status - this has a restricted vocabulary that may not be suitable for our purpose 

> Values for this term should be either "recommended" or "historical".

So we first need to agree on the status vocabulary that we want to track.
I will ask Alistair what they are doing in the OGC space.

**Comment by AaronWilton** [comment]
from Alistair: 
>   off the top of my head: no. status is often inferred, ie be the presence of a deprecation data, or superseded by property.

one approach would be to use dc:valid - but this is only a date range, so the status is inferred....

**Comment by AaronWilton** [comment]
this may be an approach:

<owl:DeprecatedProperty>true</owl:DeprecatedProperty>
<dc:valid>1997-01-01/2015-01-30</dc:valid>

**Comment by ben3000** [comment]
So this begs the question: do we put the deprecated elements into HISPID Terms 1.0 (and thus give them new camelCased names and URIs etc.) just so we can mark them as deprecated?
