### ISSUE TITLE
Use skos:exactMatch instead of owl:sameAs

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#37]
The owl:sameAs property is far more strict than skos:exactMatch, and thus may be too strict for the needs of our term definitions.

**Comment by ben3000** [comment]
Aaron, I assigned you because you were going to discuss this with your guy a bit more before.

**Comment by ben3000** [comment]
Should basisOfRecord be a sameAs/exactMatch of http://wiki.tdwg.org/twiki/bin/view/ABCD/AbcdConcept0400 for ABCD? Is this what you meant, Niels, when you said (in email): "ABCD has proper URIs for all elements and attributes in ABCD 2.06a, which we should probably use instead of the XPATHs."?

**Comment by nielsklazenga** [comment]
Yes, that is what I meant, but it was just a suggestion. If we want to run the documentation off the terms.rdf file, we still need to get the XPATH in somehow.

**Comment by ben3000** [comment]
Ah, that is what http://rs.tdwg.org/dwc/terms/attributes/abcdEquivalence is for.

**Comment by nielsklazenga** [comment]
Yes. is there an RDF with the Darwin Core terms as well? It would be nice to see how this is used.

**Comment by ben3000** [comment]
Yes, see https://github.com/tdwg/dwc/blob/master/rdf/dwcterms.rdf. I'm using this as a template for our terms.rdf, although they don't use skos or owl as much as I think we should.

**Comment by AaronWilton** [comment]
i agree, we should try and use skos/owl as much as we can.  

Within the mapping relationships of skos we have:  broadMatch, narrowMatch, relatedMatch, closeMatch, exactMatch, relatedMatch.

Note - We need to ensure we use these correctly i think, so they may have implications for inferencing down the track - e.g., exactMatch is they only one that is transitive.  Will follow this up...

"SKOS mapping properties are intended to express matching (exact or fuzzy) of concepts from one concept scheme to another, and by convention are used only to connect concepts from different schemes"

cf with skos relationships which are for relationships within a concept scheme

**Comment by AaronWilton** [comment]
from the Skos Primer - http://www.w3.org/TR/skos-primer/

> Note on skos:exactMatch vs. owl:sameAs: SKOS provides skos:exactMatch to map concepts with equivalent meaning, and intentionally does not use owl:sameAs from the OWL ontology language [OWL]. When two resources are linked with owl:sameAs they are considered to be the same resource, and triples involving these resources are merged. 

we should definitely use the skos definition rather than the OWL one.

**Comment by ben3000** [comment]
Perhaps we should use owl:sameAs when this is the case? For example, when we're doing a direct semantic copy of an element from Dublin Core or Darwin Core.

**Comment by AaronWilton** [comment]
I think we should stick with skos mapping relationships

Sent from my Windows Phone
________________________________

**Comment by nielsklazenga** [comment]
We are not using either, but use `dcterms:replaces`, `dcterms:isReplacedBy` and `dwcattr:abcdEquivalence`.
