### ISSUE TITLE
Replace NaturalOccurrence and CultivatedOccurrence with single element establishmentMeans

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#4]
The vocabularies for the NaturalOccurrence (posnat) and CultivatedOccurrence (poscul) elements that HISPID adopted from the Plant Occurrence and Status Scheme (POSS), http://www.nhm.ac.uk/hosted_sites/tdwg/poss_standard.html, do not really work for specimen data and most values do not make sense for individual-specimen records (nevertheless, some herbaria manage to deliver those values).

It seems to make much more sense to have a single element that covers these two elements and Darwin Core does just that with the term establishmentMeans. Weirdly enough, ABCD also adopted this term in the very same edition it adopted the two HISPID terms.

GBIF has got a nice vocabulary for establishmentMeans, http://rs.gbif.org/vocabulary/gbif/establishment_means.xml, which contains the following values:
* native
* introduced
* naturalised
* managed
* uncertain.
An alternative vocabulary can be found in the Apiary Project, http://www.apiaryproject.org/sites/default/files/establishmentMeansVocab.xsd, but that one is not as nice, although we could consider 'escaped' as a further subclass of 'introduced' (in the GBIF vocabulary 'naturalised' and 'managed' are subclasses of 'introduced').

So the proposal is to ditch the current two HISPID elements and replace them with the single Darwin Core element establishmentMeans and to ditch the POSS vocabularies and use the GBIF one instead.

It is important to get this right, as establishment means is important to many AVH users.

**Comment by AaronWilton** [comment]
FROM REVIEW DOCUMENT:

HISPID (including 5) used the POSS standard, which is ostensibly a Taxon-level standard. Using Taxon-level terms in an Occurrence is an error.

To do: Are we going to map this to establishmentMeans? Are we going to map from HISPID 3/4/5 to establishmentMeans? Are we going to permit a list of values or a single value? Need to review the terms in HISPID vocabulary and ensure reflect specimen level data. Prepare mapping of these resulting terms to other vocabularies.

**Comment by ben3000** [comment]
+1 the addition of taxon-level elements in previous versions of HISPID was a (recognised) error.

**Comment by AaronWilton** [comment]
Hobart 2015-10-22:  adopted
