### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#40]
We agreed in today's meeting to rename this repository to "hispid", since it no longer pertains directly to the review.

**Comment by nielsklazenga** [comment]
That was really hard.

https://help.github.com/articles/renaming-a-repository/

**Comment by nielsklazenga** [comment]
The command to hook up your local repository again is:

$ git remote set-url origin http://github.com/hiscom/hispid

This didn't work from the Git shell (with or without the 'git' bit) for me, but it did from the command prompt. I have already pushed an update since then.
