### ISSUE TITLE
How to specify dcterms:issued

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#42]
I think we should use the date of the last build of the terms.rdf document as the value for dcterms:issued in the case of new terms, but what should we do for terms we've simply copied across from HISPID 3 or Darwin Core? Try and find a useful date? Or is version 1.0 of this terms document the first time we've issued the term and thus for 1.0 it gets the date as for new terms (see above)?

**Comment by ben3000** [comment]
This will determine what to provide for dcterms:modified too.

**Comment by nielsklazenga** [comment]
I think we should use the date they are ratified. For HISPID 3, 4 and 5 we can use the dates those documents were published.

**Comment by ben3000** [comment]
OK, HISPID 3 is nominally 1 January 1996 based on the [book's reference](http://hiscom.rbg.vic.gov.au/wiki/Herbarium_Information_Standards_and_Protocols_for_Interchange_of_Data), HISPID 4 is nominally 1 August 1999 based on the [copy available at RBG Sydney](http://plantnet.rbgsyd.nsw.gov.au/HISCOM/HISPID/HISPID4/Introduction/hispid4.html), and HISPID 5 is 16 September 2007 based on the date of the first day of the TDWG conference that it was announced at, see below.

`Neish P, Richardson B, Whitbread G (2007). New standards from old: reconciling HISPID with ABCD (ABSTRACT). In Biodiversity Information Standards TDWG: the Proceedings of TDWG: Abstracts of the 2007 Annual Conference of the Taxonomic Databases Working Group: 16-22 September 2007, Bratislava, Slovakia (eds A Weitzman, L Belbin). p. 75`

**Comment by AaronWilton** [comment]
I agree they need to be the date ratified
