### ISSUE TITLE
include full URI in rdf:Description@rdf:about

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#43]
terms.rdf currently has as
 >      rdf:Description rdf:about="institutionCode"

I think it needs to be more complete, with the labels provided in prefLabel etc
cf. with DWC top element:

>    rdf:Description rdf:about="http://rs.tdwg.org/dwc/terms/acceptedNameUsage">

PS:  what is the md syntax to include xml snippets like this?   it wouldn't display for me

**Comment by ben3000** [comment]
This was correct as part of ced77bb43cd00a92ecd11a43a96ecd4a49042988 and subsequently reworked as a hash-prefixed version so that we can use a single page for the documentation in 2b6889fe46298e8ccd5fd07e2a1e436d7c17a825.
