### ISSUE TITLE
Removal of Special Geographic Unit (sgu)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#45]
FROM REVIEW:

**Special Geographic Unit**
HISPID 3 (sgu): The special geographic recording unit describes specific conservation areas and other nature reserves of Country of Origin field
HISPID 5 / ABCD (AreaClass = “Special Geographic Unit” + AreaName): as above.
HISPID 2015: Proposed for removal

**Comment by nielsklazenga** [comment]
+1

**Comment by ben3000** [comment]
No problem here. This sort of field should be calculated from lats/longs.

**Comment by AuBiodiversity** [comment]
agreed

**Comment by afuchs1** [comment]
agreed

**Comment by ben3000** [comment]
+1

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed
