### ISSUE TITLE
Proposal to remove atomised Latitude and Longitude fields (latdeg, latmin, latsec, latdir, longdeg, longmin, longsec, longdir)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#48]
The following fields are proposed for removal:
latitudeDegree (latdeg)
latitudeMinute (latmin)
latitudeSecond (latsec)
latitudeRegion (latdir)
longitudeDegree (longdeg)
longitudeMinute (longmin)
longitudeSecond (longsec)
longitudeRegion (longdir)

**Comment by afuchs1** [comment]
to be replaced by verbatimLatitude, verbatimLongitude

**Comment by AaronWilton** [comment]
and/or the verbatimCoordinateSystem (and related fields) as appropriate

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed
