### ISSUE TITLE
Proposal to remove Spatial Grid fields - sgz, sge, sgn

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#49]
Outcome from Workshop - unresolved whether these are retained.  Discussion that this data would be provided in the verbatimCoordinates and related fields
Not included in HISPID2105.xlsx

FROM REVIEW document:

Spatial Grid, Zone Number
DarwinCore: - concatenate into verbatimCoordinates http://rs.tdwg.org/dwc/terms/verbatimCoordinates 
HISPID 4(sgz): The numerical Zone corresponding to the central meridian and origin upon which the easting is based. Supply an integer between 1 and 60 inclusive.
HISPID 2015: the numerical Zone corresponding to the central meridian and origin upon which the easting is based. Supply an integer between 1 and 60 inclusive.
ABCD: abcd://Unit/Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesUTM/UTMZone
Spatial Grid, Easting
DarwinCore:- concatenate into verbatimCoordinates http://rs.tdwg.org/dwc/terms/verbatimCoordinates 
HISPID3 (sge): the Map Grid Easting reference of the locality from which the plant specimen was collected.
HISPID 2015: the Map Grid Easting reference of the locality from which the plant specimen was collected.
ABCD: abcd://Unit/Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesUTM/UTMEasting

Spatial Grid, Northing
DarwinCore:- concatenate into verbatimCoordinates http://rs.tdwg.org/dwc/terms/verbatimCoordinates 
HISPID3 (sgn): the Map Grid Northing reference of the locality from which the plant specimen was collected.
HISPID 2015: the Map Grid Northing reference of the locality from which the plant specimen was collected.
ABCD: abcd://Unit/Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesUTM/UTMNorthing

**Comment by ben3000** [comment]
I don't currently have enough information to decide one way or another. Maps still use them, but I don't deal direct with people who use them in preference to lats and longs. We have plenty of specimens (18000+) where these were the primary source of the coordinate, with new entries received in the last few weeks.

**Comment by nielsklazenga** [comment]
They are actually not so much removed as replaced by `dwc:verbatimCoordinates` (and `dwc:verbatimSRS` and `dwc:verbatimCoordinateSystem`). We still have all the old HISPID grid fields in our (new) database, but if we would deliver them in HISPID (I don't think we do at the moment) they would need to be conver/catenated to the Darwin Core terms. We have the problem of many incomplete UTM strings, because people forget to provide the zone and/or the grid (AMG/MGA etc.).

**Comment by afuchs1** [comment]
Is this a reason to keep the fields separate otherwise it is near impossible to make sense of them (even if they are wrong) especially if they are the only coordinates recorded.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Cross reference this issue to verbatimCoordinates.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed
