### ISSUE TITLE
Proposed for removal - taxonRemarks (namcom)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#51]
FROM Review document:

**taxonRemarks**

Darwin Core:  Comments or notes about the taxon or name.
HISPID 3 (namcom):  Any comments about the name of the plant are transferred in this field.
ABCD (..//NameComments):  Any free text comments related to the name
HISPID 2015:   proposed for removal for specimen data, as there is already occurrenceRemarks and identificationRemarks.

**Comment by nielsklazenga** [comment]
Ben correctly observed that issue #66 belongs here. This means that I am not in favour of removing `taxonRemarks`.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
We are keeping the term.
