### ISSUE TITLE
Proposal to remove numberOfSheets (numshe)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#52]
FROM Review document:

**numberOfSheets**
HISPID 3 (numshe):  The number of herbarium sheets, packets, boxes, etc., that make up the specimen represented by this record.
HISPID 2015: Proposed for removal

**Comment by ben3000** [comment]
+1 This value can be calculated from other data (in a well-normalised data structure).

**Comment by afuchs1** [comment]
That's assuming that the de-normalised data is provided to Darwin Core and is injested as such. If a herbaria does not store its data like this is there value when compiling records for loans to include the number of sheets or is this loan term?

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed to retain this term and move to the Transaction class

**Comment by AaronWilton** [comment]
added to terms.rdf
