### ISSUE TITLE
typeOfCultivatedMaterial (tcul)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#53]
FROM Review:

**typeOfCultivatedMaterial**
HISPID 3 (*tcul*):  A code indicating the presence of living material for cultivation, collected at the time of collection of the specimen on which the record is based.
HISPID 2015: 
Vocabulary:  cutting, cytological, division, plant, seed

Comment:  requires review ->  is this concept useful to provide, or better to indicate presence of cultivated material, but then why not provide that as a linkage

**Comment by AaronWilton** [comment]
Note - this field is not currently listed in HISPID2015.xlsx

**Comment by ben3000** [comment]
We do not store this data.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed to remove
