### ISSUE TITLE
provenanceTypeFlag (prot)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#54]
proposal to adopt the ITF field name and definition (including vocabulary)

FROM REVIEW DOCUMENT:
*provenanceCategory (ITF: provenanceTypeFlag)*
Darwin core: -
HISPID 3 (prot):  A code to indicate the provenance of the accession of living material represented by the herbarium voucher.
HISPID 2015:  the provenance of the living material from which this collection object was taken
Vocabulary:  propagule from wild source plant in cultivation; accession not of wild source; insufficient data to determine category; accession of wild source
Still under discussion

Code | Meaning
------ | -----------
W | Accession of wild source
Z | Propagule(s) from a wild source plant in cultivation
G | Accession not of wild source
U | Insufficient data to determine which of the above categories apply

Code | Definition
---- | --------
W | Accessions which originate from material collected in the wild. The accession has not been propagated further, except in the case of plants that may have been grown on from the original stock. The accession may have come directly from the wild, or from a botanic garden or gene bank acting as a distribution centre. Recent accessions in this category should have accompanying collection data, but the category may also include older accessions which are known to be of direct wild origin but which do not have such additional data.
Z | Accessions derived by propagation directly from an original wild source plant. The method of propagation must be recorded in the Propagation History field. If the propagation is not directly from the original wild source plant, a complete history of the intermediate propagation steps must be known, otherwise the accession should placed in the following category.
G | Accessions derived from cultivated plants where the immediate source plant does not have a propagation history that can be traced in detail to a wild plant. This category normally includes all cultivars.
U | Accessions where there is insufficient data or knowledge to know which of the three above categories applies.

**Comment by nielsklazenga** [comment]
Agreed. This vocabulary is widely used at botanical gardens worldwide.

**Comment by afuchs1** [comment]
Agreed.

**Comment by ben3000** [comment]
+1

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Adopt ITF-2 vocabulary.
