### ISSUE TITLE
Proposal to remove propagationHistory (prohis)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#55]
FROM REVIEW DOCUMENT

**propagationHistory**
HISPID 3 (prohis):  A code to indicate the nature of the production of the living plant material vouched by the herbarium material, for use in association with the previous field, Provenance Type Flag.
HISPID 2015: Proposed for removal

**Comment by afuchs1** [comment]
agreed

**Comment by ben3000** [comment]
+1 There is no field in our system that stores this data.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed
