### ISSUE TITLE
Proposal to remove Donor Type Flag (dont)

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#56]
FROM Review document:

**Donor Type Flag**
HISPID 3 (dont):  A code to indicate the type of donor from which the accession was obtained.
HISPID 2015: Proposed for removal

**Comment by ben3000** [comment]
+1 There is no field in our system that stores this data.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed
