### ISSUE TITLE
Use dwcattributes:organizedInClass for grouping?

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#62]
We're grouping terms by values such as "Occurrence", "Record level terms" and the like. Should we used dwcattributes:organizedInClass to group our terms like [Darwin Core](https://github.com/tdwg/dwc/blob/master/rdf/dwcterms.rdf#L69) does?

**Comment by nielsklazenga** [comment]
Works for me. Will you also add terms for the classes, like Darwin Core RDF does? Please note that our classes are not the Darwin Core classes, even though many have the same name, so you should put them in the [hispid](http://hiscom.chah.org.au/terms) namepace.

**Comment by ben3000** [comment]
I'm happy to do that.

**Comment by ben3000** [comment]
dwcattributes:organizedInClass [makes no attempt to domain or range the values assigned to it](https://github.com/tdwg/dwc/blob/master/terms/attributes/dwcattributes.rdf#L58), thus we can use it as-is. We might confuse our users if we do diverge from the group used in Darwin Core. Do we have many/any examples of this?

**Comment by nielsklazenga** [comment]
Yes, we do. All the non-Darwin Core terms that have not been grouped in custom HISPID classes. I had suggested earlier to re-circumscribe the Darwin Core classes in the HISPID namespace, if there are added elements, so that the HISPID class is an extension of the Darwin Core class. Not sure if that is appropriate in RDF, but I think that is actually the way that will confuse users the least.

**Comment by ben3000** [comment]
OK, so I'm using the DWC organizedInClass term to link to the HISPID-namespaced group we're using in our terms. There is thus no equivalence between the Darwin Core and HISPID Terms groups.

**Comment by nielsklazenga** [comment]
Yes, that's right. Will look if there are any classes that have no extra elements. Is it possible in RDF to indicate that the HISPID class is an extension of the Darwin Core one? Or could we just do a mapping?

**Comment by ben3000** [comment]
Just like the other terms, we could do a skos:exactMatch, skos:closeMatch, skos:broader, or skos:narrower to explain the relationship to the DWC grouping without the full RDF mapping.

**Comment by nielsklazenga** [comment]
Excellent. Works for me.

**Comment by ben3000** [comment]
Once I add the grouping terms, we're at the point that we have to leave the Excel spreadsheet behind, as these aren't in the spreadsheet, and perhaps it is about time anyway.

**Comment by nielsklazenga** [comment]
Yep, works for me again. Spreadsheet is becoming quite unwieldy too. And we can recreate it from the RDF at any time, if needed.

**Comment by ben3000** [comment]
OK, I'll get this done today. You might want to finesse the groups as we've discussed in case my recollection of their definition/etc. is dodgy.

**Comment by ben3000** [comment]
Should I sort the terms by name (like Darwin Core) or by group and name, or leave it as-is?

**Comment by nielsklazenga** [comment]
I think while we are still actively working on it, it might be best to sort them by group and then name.

**Comment by nielsklazenga** [comment]
Hi Ben, I just noticed that the [Location](http://tdwg.github.io/dwc/terms/index.htm#Location) class in Darwin Core is in the Dublin Core namespace, even though Darwin Core adds many of its own properties to it. Therefore, I think we can just leave the classes we adopted from Darwin Core in the Darwin Core namespace.

**Comment by ben3000** [comment]
Probably all that is necessary is to change, e.g. http://chah.org.au/hispid/terms/1.0-SNAPSHOT/#CollectionObject to the equivalent group rdf:resource in Darwin Core.

**Comment by nielsklazenga** [comment]
I don't understand.

**Comment by ben3000** [comment]
Sorry, I'm looking at terms.rdf and thinking about what needs changing. I just placed group terms into terms.rdf, and your saying they shouldn't have a HISPID namespace, which is effectively what the uri for our group terms represent.

So a group term such as [Occurrence](https://github.com/hiscom/hispid/blob/86d26481b8dffceeac2a42ef0357607b78f86ffe/terms.rdf#L753) needs to either point to the [uri for the equivalent group term in Darwin Core](http://rs.tdwg.org/dwc/terms/Occurrence) (if we want the group to continue to exist in HISPID), or go away entirely, and individual HISPID terms just have an `organizedInClass` property with a rdf:resource value of http://rs.tdwg.org/dwc/terms/Occurrence.

I think I prefer the latter, assuming we agree wholly with Darwin Core on the group names and semantics.

**Comment by nielsklazenga** [comment]
I see. And I agree. Was just confused as you chose as your example one of the classes that is not in Darwin Core.

**Comment by ben3000** [comment]
Yeah, I realised that while typing my reply :) But it forms a useful case, we have to mint new group terms if Darwin Core doesn't have them.

**Comment by ben3000** [comment]
I think this is complete.
