### ISSUE TITLE
Need an equivalent to dwcattributes:abcdEquivalence for HISPID equivalence

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#63]
In many cases, a HISPID term can't be linked directly (semantically, using `rdf:resource`) to a single element in a previous standard because it took several elements to convey the same meaning.

A case in point is [`establishmentMeans`](https://github.com/hiscom/hispid/blob/master/terms.rdf#L195), which maps to the two definitions `posnat` and `poscul`, both from HISPID 3 and HISPID 4. We can't supply a single `skos:exactMatch`, but we could supply several: one for each equivalent. However, even this doesn't work properly because it was the collection of elements that conveyed the same meaning. Perhaps in this case we use `skos:relatedMatch` and relatives instead? And then place an explanation of the difference in the text of the `skos:scopeNote`.

**Comment by nielsklazenga** [comment]
I think we should use `dcterms:replaces` and `dcterms:isReplacedBy` instead.

**Comment by ben3000** [comment]
Completed.
