### ISSUE TITLE
taxonRemarks

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#66]
This is the old HISPID _namcom_ and ABCD _NameComments_ field. We still have it as 'under consideration', as we couldn't think of a use for it in specimen records.

I think I just found a use. Among my Chilean Dicranolomas I still have two entities that I haven't been able to match confidently to described taxa yet. I currently call them _Dicranoloma sp. C_ and _Dicranoloma sp. D_. Last week I databased them as such, with a _taxonRemark_ that these are manuscript names in my South American _Dicranoloma_ revision.

**Comment by ben3000** [comment]
#51
