### ISSUE TITLE
dwc:dataGeneralizations and dwc:informationWithheld

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#67]
I think we should add [`dataGeneralizations`](http://rs.tdwg.org/dwc/terms/dataGeneralizations) and [`informationWithheld`](http://rs.tdwg.org/dwc/terms/informationWithheld) to the standard. `dataGeneralizations` will mostly be populated by ALA for AVH data, but that doesn't mean we shouldn't have it in HISPID. Also, there might be instances that are not caught by the Sensitive Data Service, but we still need to generalise the georeference, for example for certain weeds, or drugs. `informationWithheld` can also be used for private information.

**Comment by ben3000** [comment]
Yep, +1 from me.

**Comment by AaronWilton** [comment]
+1

**Comment by AaronWilton** [comment]
done - i think we can close this
