### ISSUE TITLE
Exsiccata

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#7]
Not sure if I want to add exsiccata, but it strikes me as odd that a herbarium data standard wouldn't deal with exsiccata. If we add them, terms needed would be exsiccataSeries, exsiccataFascicle and exsiccataNumber.

**Comment by AaronWilton** [comment]
I agree - an odd omission.  I think these are worth adding

**Comment by nielsklazenga** [comment]
Thanks, will add them in the __CollectionObject__ class.

**Comment by AaronWilton** [comment]
Three fields proposed:

Field | Definition
----- | ----------
exsiccataSeries | Exsiccata series
exsiccataFascicle |  Fascicle in exsiccata series
exsiccataNumber | Number in exsiccata series

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Approved.
