### ISSUE TITLE
Barcode field

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#70]
A while back, I raised with Miles the issue that in the majority of AVH records the `catalogNumber` doesn't match the barcode on the herbarium sheet (or other preparation). This poses problems for matching up duplicates, but also for finding barcodes cited in publications, or in GenBank, or even finding the AVH record for the specimens someone has on loan.

It is near impossible, and certainly not advisable, to change catalogue numbers in AVH, as they are part of the Darwin Core triplet that "uniquely" identifies the record. Miles suggested we just create a 'barcode' field. I think that is a good solution.

**Comment by ben3000** [comment]
We already have a barcode field, and could thus provide this immediately.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed to add to PreservedSpecimen class

**Comment by AaronWilton** [comment]
done
