### ISSUE TITLE
Subject category

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#71]
`Iptc4xmpExt:CVterm` is deprecated in the new edition of the [IPTC metadata standard](http://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata). We should use `Iptc4xmpExt:AboutCvterm` instead.

**Comment by nielsklazenga** [comment]
This relates to issue #5. Couldn't find that earlier.

**Comment by AaronWilton** [comment]
Audubon Core allows terms from recommended vocabularies to be provided as unqualified literals , but requires they are full URI's otherwise.

My reading is that IPTC now requires this to be a URI.  (I could be wrong on this...)

I think we should always require they are full URI's - agree?

**Comment by AaronWilton** [comment]
if we use full URI's then does subjectCategoryVocabulary become redundant?

**Comment by nielsklazenga** [comment]
Yes and yes.

**Comment by nielsklazenga** [comment]
We might actually want to keep the old terms as long as Audubon Core does and just already add `Iptc4xmp:AboutCvterm`.

**Comment by AaronWilton** [comment]
hmm, i think your comment before regarding history is appropriate here too  - let's not introduce unnecessary baggage - especially when the mapping to the two terms should be relatively simple.

Assume we need agreement at the teleconference tomorrow.

Proposal - update the subjectCatergory to use the new IPTC term; not adopt subjectCategoryVocabulary.

**Comment by nielsklazenga** [comment]
I wouldn't call it unnecessary garbage and we are not introducing it, they are already in Audubon Core. I was against including anything dealing with images, remember? `Cvterm` is at the moment much more useful to us than `AboutCvterm`.

**Comment by AaronWilton** [comment]
Teleconference:  agreed to attempt jump to new term
