### ISSUE TITLE
Change CollectionObject to PreservedSpecimen

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#74]
`PreservedSpecimen` is an existing Darwin Core class, so it makes sense to use it instead of minting our own. The properties we have in the CollectionObject class fit well with the properties (well, only one property, `materialSampleID`, actually) that Darwin Core has under `MaterialSample`, `LivingSpecimen`, `PreservedSpecimen` and `FossilSpecimen`, so, if we ever want to use the properties for other things than preserved specimens, we can do that.

**Comment by ben3000** [comment]
`+1`, I'm already finding the continued proliferation of specimen-like object nouns disconcerting, so one less is a good thing. Those who actually need a `LivingSpecimen` (perhaps botanic gardens) could of course use that.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed
