### ISSUE TITLE
parentEventID

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#75]
Miles and I have independently of each other suggested that [`dwc:parentEventID`](http://rs.tdwg.org/dwc/terms/parentEventID) could be used for expeditions, case in point being the BushBlitz expeditions, and Alexis is bringing this to FCIG as a suggestion. Alexis thinks they can put names of expeditions in this field, which is anathema to me (and all of us, I'm sure), but a URL to a web page I would use no problem. We could still use `hispid:collectingTripName` for the name of the expedition and will have all other fields in the Event class (e.g. `eventDate`, `eventRemarks`) for all other information relating to collecting trips.

I thought I put in this issue last week, but I can't find it, so it is possible that this is a duplicate issue.

**Comment by ben3000** [comment]
+1, I can only find a reference to `hispid:collectingTrip` in this Github project though, is `hispid:collectingTripName` a newer proposal?

**Comment by nielsklazenga** [comment]
It wasn't meant to be, but it could be, as it is a better name for the term (#8).

**Comment by ben3000** [comment]
+1 for a real ID (even a URI) over a name or some chunk of text for the content for the parentEventID element.

**Comment by AaronWilton** [comment]
Hobart 2015-10-22:  Adopted
