### ISSUE TITLE
More GUIDs

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#76]
`eventID` from issue #2 hasn't been picked up yet. I think we should add it. MEL is already delivering it, or could any day, as it is in our database. If we are going to use `parentEventID` for expeditions (#75), it is a bit weird not to have `eventID`. I would also like to add `locationID`, which we also already have in our database.

Other GUIDs that we don't have to mint ourselves, but should get from elsewhere are `taxonConceptID` and `higherGeographyID`. We have already added `scientificNameID`, which I don't remember us discussing, but I got it from the notes of the HISPID Review workshop, so we must have and it makes sense, as we presumably had the APNI identifiers in mind. I would like to use `higherGeography`. I don't have a use for `taxonConceptID` at the moment, but I think it should be added to HISPID anyway, as I have this idea in my head that a class represents a resource and hence should have an identifier. I do see a problem, however, of people confusing taxa and names and will use `taxonConceptID` when it would be more appropriate to use `scientificNameID`. More discussion required probably. We don't have to do everything right away.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Add locationID.
Term Name: locationID
Identifier:	http://rs.tdwg.org/dwc/terms/locationID
Class:	http://purl.org/dc/terms/Location
Definition:	An identifier for the set of location information (data associated with dcterms:Location). May be a global unique identifier or an identifier specific to the data set.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed
