### ISSUE TITLE
institutionCode vs collectionCode

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#77]
From Darwin Core Guide:
**institutionCode**
The name (or acronym) in use by the institution having custody of the object(s) or information referred to in the record.
Comment:	Examples: "MVZ", "FMNH", "AKN-CLO", "University of California Museum of  Paleontology (UCMP)". For discussion see http://terms.tdwg.org/wiki/dwc:institutionCode

**collectionCode**
The name, acronym, coden, or initialism identifying the collection or data set from which the record was derived.
Comment:	Examples: "Mammals", "Hildebrandt", "eBird". For discussion see http://terms.tdwg.org/wiki/dwc:collectionCode
Details:	collectionCode

*Issue*:  we current have institutionCode = the Index Herbariorum acronym, and  collectionCode = a smaller subdivision.   

I suggest that this inconsistent with the definitions and appears to be discordant with at least the sample of the records I went through in GBIF.    I think institutionCode should be for the name or code of the institute (and I don't class a herbarium collection within an organisation as an institute).  For example, institutionCode would be "Landcare Research" and the collectionCode's within that would be CHR, PDD and NZAC respectively for our three natural history collections collections ...

(I realise there may be downstream impacts for ALA, but lets not be limited by that at this stage and rather focus on correct usage here.  THEN if we agree that a different usage is preferred at that stage open those discussions/considerations.)

**Comment by nielsklazenga** [comment]
I would consider herbaria institutions. The fact that they are often part of larger institutions doesn't make them less of an institution. So the National Herbarium of Victoria is an institution and so is the Allan Herbarium. Herbaria can have multiple collections, such as a 'bryophyte collection', 'spirit collection' or 'Ilma G. Stone collection'. I'd use institutionCode for herbaria and collectionCode for those smaller collections, which is exactly what the Darwin Core examples are doing. Most AVH providers have just the one collection, so can use the same code for both.

**Comment by ben3000** [comment]
Our usage is the same as Niels'. The institution is PERTH (a herbarium, not a State Government department). I'd say that this matches the institutionCode example "University of California Museum of Paleontology (UCMP)", which identifies the Museum as the important object, not the University.

**Comment by AaronWilton** [comment]
Had a look at what is getting submitted in these fields to GB IF - a real mess.....  
Will close this issue (for now!)
