### ISSUE TITLE
Reduce the number of (apparently) duplicate documents

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#79]
I'm a bit confused about the number of RDF files, terms.rdf, draft-terms.rdf, terms/hispid2015.rdf, terms/hispidterms.rdf. We need to store only source in Github. Any build output should not be checked in, as it is output from the source.

My understanding is that terms.rdf is the primary source for change, and draft-terms.rdf is where we place terms due for discussion prior to their addition to the main terms.rdf file. This isn't set in stone, but we currently have too many (apparent) sources for terms.

**Comment by nielsklazenga** [comment]
Yes, I made a bit of a mess of that directory by pushing all the files that I had to GitHub. So we'll do a clean-up. I think the plan was to have just the terms.rdf, but have the one we put changes in in a different branch. We hadn't made a decision about that though.

**Comment by AaronWilton** [comment]
Use we need to discuss this - I have been wondering about just having  the history file, then deriving everything (and I mean everything) off that using xslt...  at the moment I am updating the vocabs and terms, and will have to reconcile the history file....  I would only then have the master terms document and xslt and xsl necessary to build the outputs.

We definitely need to discuss...  (but after we have this version out)

**Comment by nielsklazenga** [comment]
I like the idea of running everything from the one document, but I think it will make it harder to maintain and easier to make mistakes. So I prefer to keep the terms.rdf for the current terms and the history.rdf for the terms we no longer use.

I would be happy for one of us just implementing their preferred solution and then we'll see how well it works (or not). It's not like we are going to irreparably lose anything.

**Comment by AaronWilton** [comment]
going to have to get pretty close to that to try and reconcile this beast I reckon, so I will tentatively put my hat in the ring to have a go...

**Comment by AaronWilton** [comment]
I believe there are 2 issues here - one the number of files has been dealt with very nicely by Niels.
the second issue is the structure the terms rdf - will create a new issue for that as beyond the scope we can achieve in current review.  (#101)
