### ISSUE TITLE
Expedition or collecting trip

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#8]
A field to indicate the expedition or collecting trip where a specimen has been collected has come up in discussions with FCIG a couple of times before and most recently in relation to Bush Blitz. Options in ABCD are //Unit/NamedCollectionsOrSurveys or //Unit/Gathering/Project/ProjectTitle. I'd prefer the latter, because it is under Gathering.

There is not really an equivalent in Darwin Core. In the new Event Core (which is currently an Event extension) there is a projectID element, which is given as a Darwin Core element, but appears to be not really. It is also an ID, rather than a name or title, so it might be better to create a custom element. Whatever we do, it needs to be delivered to AVH under the same term that FCIG chooses.

**Comment by nielsklazenga** [comment]
Added a placeholder element __collectingTrip__ in the HISPID namespace.

**Comment by AaronWilton** [comment]
+1

**Comment by ben3000** [comment]
+1, definitely prefer the //Unit/Gathering/Project/ProjectTitle approach.

**Comment by nielsklazenga** [comment]
This discussion has been picked up again, and I have been emailing with Alexis (FCIG), Michael and Miles (ALA) last week.

Darwin Core now has a `[parentEventID](http://rs.tdwg.org/dwc/terms/parentEventID)` property in the `[Event](http://rs.tdwg.org/dwc/terms/Event)` class, which, because it is in Darwin Core, might be acceptable to FCIG. I have a problem with putting a name in an ID field, but I wouldn't mind putting a URL to the BushBlitz website, or preferably a page for a particular BushBlitz event, in `parentEventID`. This is what Alexis is bringing to FCIG. We can still use `collectingTrip` (or whatever else we are going to call it) for the name of the trip and for other expeditions that may not have identifiers.

**Comment by ben3000** [comment]
+1 for a real ID (even a URI) over a name or some chunk of text for the content for this element.

**Comment by nielsklazenga** [comment]
Hobart, 2015-10-20:
Example: "Bush Blitz Skullbone Plains 2012"

**Comment by DNAdl8** [comment]
Do we need 'Date Start' and 'Date End' for collectingTripName? There's two date terms in the Event Class but this refers to the date of collection of the Specimen, not the collecting trip dates? Sorry I should have raised this at the AGM but I forgot..

**Comment by nielsklazenga** [comment]
I think this is more a matter for implementation in individual herbarium databases than for HISPID. In HISPID now, if you want to deliver detailed collecting trip information, you'll need to deliver a separate Event record for the parent event (collecting trip). If you do that, `eventDate` and `eventRemarks` can be applied to the collecting trip. I don't think we should try to denormalise this. If people want to deliver more detailed collecting trip information than just the name in an occurrence record, for example an AVH record, they can use `eventRemarks` for that.

**Comment by DNAdl8** [comment]
Thanks Niels, I suspected the existing date fields could be used.. Just wanted to put it out there..

**Comment by DNAdl8** [comment]
Bush Blitz are happy to go with the proposed expedition names in the format Bush Blitz [year] [site/area name] – with no special characters in the name (hyphens, apostrophes etc)

**Comment by nielsklazenga** [comment]
I think HISPID is up-to-date with what is discussed here. It would be good to add the collecting trip info to `eventRemarks` as well, so we can deliver it in Darwin Core as well, but that is implementation.
