### ISSUE TITLE
nearestNamedPlace

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#81]
We do not want to use this as generalised locality any more. There are still two use cases: (1) a nearest named placed given by a collector when the collecting locality doesn't have a name or is obscure and (2) the place name the georeference is based on when the name of the locality can't be found in any gazetteer. The latter use case probably deserves its own term.

**Comment by nielsklazenga** [comment]
Hobart, 2015-1020:
We feel that all detail can be expressed in the fields that are already available in the Location class, so propose to deprecate the term.

**Comment by AaronWilton** [comment]
Hobart 2015-10-22:  Approved for removal
