### ISSUE TITLE
Identification method

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#84]
Hobart, 2015-10-20:
We think it will be good to add a term for identification method, as we will increasingly obtain identifications by other methods than the traditional identifications based on morphology. Term should have a vocabulary. Possible examples include: 'BLAST!', 'DNA barcode', 'Morphology', ... etc.

**Comment by AaronWilton** [comment]
label = identificationProtocol to match georeference term?

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed to added

**Comment by AaronWilton** [comment]
added term - please comment on definition and vocabulary:

STRAWMAN = 
definition:  The protocol used by the identifier to establish the identification of the specimen.
vocabulary terms:  BLAST, barcode, text [morphological comparison with electronic or print text], image [morphological comparison with an image], specimen [morphological comparison with specimen]

**Comment by nielsklazenga** [comment]
Replace 'protocol' with 'method' (or 'protocol or method') and the definition is all right.
