### ISSUE TITLE
Add verbatim scientific name field

### ISSUE THREAD

**Issue by AaronWilton** [hiscom/hispid#85]
Hobart, 2015-10-20:
Propose to add a new term for the verbatim scientific name as provided by the identifier

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed to term verbatimIdentification for the verbatim name provided by the identifer

**Comment by AaronWilton** [comment]
added to Identification Group

**Comment by nielsklazenga** [comment]
I was thinking Taxon class when I saw this, as that is where scientificName is, but Identification class is right.

**Comment by nielsklazenga** [comment]
I added the following skos:scopeNote:

> verbatimIdentification is meant to include the entire name string as given by the determiner, including any identification qualifiers and addenda. It is not meant to include the name of the determiner, identification date, remarks etc.

**Comment by nielsklazenga** [comment]
And added examples:

> Riccia aff. multifida Step.,
> Amanita ?pantherina (DC. : Fr.) Secr.
> Erica cf. hirtiflora Curt.
> Acacia sp.
> Bryum s.l.
