### ISSUE TITLE
Add associatedOccurrences

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#86]
MAHC/HISCOM, Hobart, 2015-10-21:
Add associatedOccurrences. For host–parasite relationships for which both sides of the relationship are herbarium specimens. Use same associationType vocabulary as for associatedTaxa.

See #20.

**Comment by AaronWilton** [comment]
Hobart 2015-10-23:  Agreed  (key value pairs using Type and OccurrenceID)

**Comment by AaronWilton** [comment]
added to terms rdf
