### ISSUE TITLE
How do local implementations of HISPID concepts flow into AVH and services when diffferent institutions implement differently

### ISSUE THREAD

**Issue by afuchs1** [hiscom/hispid#9]
Example : CANB has implemented a 'local abundance’ field which maps to the HISPID concept 'frequency', while other herbaria appear to put abundance data in the ‘notes’ and this is visible on the AVH and CANB's is not, even in the ‘original vs processed’ view.

Also how do other herbaria handle this data when they download our exchange data & feed it into their databases.

In this example the concept  ‘frequency’ in HISPID is mapped to the ABCD element

Units/Unit/Gathering/SiteMeasurementsOrFacts/SiteMeasurementOrFact/MeasurementOrFactAtomised/

If you query BioCASe for CANB:591622.1 you will see it reported as follows:

```xml
<abcd:SiteMeasurementsOrFacts>
 <abcd:SiteMeasurementOrFact>
    <abcd:MeasurementOrFactAtomised>
      <abcd:Parameter>frequency</abcd:Parameter> 
      <abcd:LowerValue>Common, localised.</abcd:LowerValue> 
      <abcd:IsQuantitative>false</abcd:IsQuantitative> 
    </abcd:MeasurementOrFactAtomised>
 </abcd:SiteMeasurementOrFact>
</abcd:SiteMeasurementsOrFacts>
<abcd:Biotope>
  <abcd:Text language="en-au">Flat. Loamy soil over serpentinite. Layered Eucalyptus sp. aff. macrorhyncha woodland with Acacia brownii adn Dicanthium spp.</abcd:Text> 
</abcd:Biotope>
<abcd:Notes language="en-au">Erect herb to 30 cm tall.</abcd:Notes>
```

So we are reporting it; if the Site Measurement name is used in the AVH original data screen, you may be able to confirm whether this information does actually make its way into the system.

**Comment by ben3000** [comment]
I've always considered it a job of mine to convert/filter our data on export to BioCASE (and thus AVH/ALA). Thus, the data isn't provided in its exact original form, rather in the form mandated/suggested by HISPID (or other standard).
