### ISSUE TITLE
Are we placing a controlled vocabulary on any Darwin Core terms?

### ISSUE THREAD

**Issue by ben3000** [hiscom/hispid#90]
We can't do that as it changes the semantic of the DwC term.

**Comment by nielsklazenga** [comment]
No, it doesn't. In fact, Darwin Core recommends using controlled vocabularies for many of its terms.

**Comment by ben3000** [comment]
Even if the change we're making is in DwC's namespace?

**Comment by nielsklazenga** [comment]
I think we are talking different things. I think you are talking XML Schema Definition; I am not.

**Comment by ben3000** [comment]
I wasn't, but I am asking a question that I think you've answered now. Ta.

**Comment by AaronWilton** [comment]
I agree with Niels - apply a controlled vocabulary shouldn't change the meaning (if it did we are misapplying the term), in fact many of the terms in DWC recommend application of a controlled vocabulary, but do not provide or clearly only provide an example.

Closing this issue.
