### ISSUE TITLE
Permit or Consent

### ISSUE THREAD

**Issue by nielsklazenga** [hiscom/hispid#95]
At the HISCOM meeting, at the very last minute, a suggestion was made that the word 'Permit' not sufficiently accommodates the use cases for the Permit class and a proposal was made to change the name of the class to 'Consent'. I was the only one who disagreed, but I eventually gave in (consented) because I wanted it to be over with and to go home.

Nobody does their best thinking on a Friday afternoon after three days of meetings (four days for some of us) and it is not wise to make snap decisions, especially when there is no agreement. Also, no GitHub issue was opened, so we could pretend it never happened. However, Laurence's point (Laurence was the johnny-come-lately who made the proposal) is well-taken. So, how about __PermitOrConsent__ – in analogy to [MeasurementOrFact](http://rs.tdwg.org/dwc/terms/MeasurementOrFact)? This is not a compromise, but the term I think we were searching for last Friday and conveys exactly what we want it to convey.

We need to change the names and descriptions of all or most of the properties of the class accordingly.

**Comment by nielsklazenga** [comment]
Ah, there is an issue (#10).

**Comment by DNAdl8** [comment]
I support Niels suggestion to name this term PermitOrConsent. At least it is inclusive and spells out what it incorporates. We struggled to find the right word at the AGM, but I think this 'does the job'!

**Comment by DNAdl8** [comment]
DNAdl8 = Donna Lewis

**Comment by afuchs1** [comment]
+1

**Comment by AaronWilton** [comment]
+ 1
( I think this issue should be re-opened and number #10 re-closed)

**Comment by laurencepaine** [comment]
I concede that PermitOrConsent is probably the best term for the concept that we will be able to derive. +1

**Comment by ainsleyongit** [comment]
+1

**Comment by AaronWilton** [comment]
updated terms and vocabulary
